// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace DataAccessLayer.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig1));
        
        string IMigrationMetadata.Id
        {
            get { return "202104161148487_mig1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
